-- 도서관 회원
create table MEMBER(
    ID VARCHAR(10) PRIMARY KEY,
    PASS VARCHAR(10) NOT NULL,
    NAME VARCHAR(10) NOT NULL,
    REG_DATE DATETIME DEFAULT NOW() NOT NULL,
    PHONE_NO VARCHAR(11) NOT NULL,
    EMAIL VARCHAR(30) DEFAULT NULL,
    REG_LIB VARCHAR(10) NOT NULL,
    AGREE CHAR(1) DEFAULT 'Y',
    CONSTRAINT MEMBER_REQ_LIB_FK FOREIGN KEY (REQ_LIB) REFERENCES LIBRARY(LIB_NAME),
    CONSTRAINT MEMBER_NAME_CHECK CHECK (REGEXP_LIKE(NAME,'^[^[:space:]]+$')),
    CONSTRAINT MEMBER_PHONE_NO_CHECK CHECK (LENGTH(PHONE_NO) <= 11),
    CONSTRAINT MEMBER_AGREE_CHECK CHECK (AGREE IN ('Y','N')),
    CONSTRAINT MEMBER_ID_CHECK CHECK (REGEXP_LIKE(ID,'^[^[:punct:][:space:]]+$')),
    CONSTRAINT MEMBER_PASS_CHECK CHECK (REGEXP_LIKE(PASS,'^[^[:punct:][:space:]]+$')),
    CONSTRAINT MEMBER_EMAIL_CHECK CHECK (REGEXP_LIKE(EMAIL,'^[^[:punct:][:space:]]+@[^[:punct:][:space:]@]+\\.[^[:punct:][:space:]@]+(\\.[^[:punct:][:space:]@]+)*$'))
);

-- 테이블 기본값 확인 문장
create table member(
    ID VARCHAR(10) PRIMARY KEY,
    REG_DATE DATETIME DEFAULT NOW() NOT NULL
);
insert into member(id) values('a');
select * from member;
select now();
drop table member;
-- 정규식 확인
SELECT REGEXP_LIKE('aa@a.a.a aaa', '^[^[:punct:][:space:]]+@[^[:punct:][:space:]@]+\\.[^[:punct:][:space:]@]+(\\.[^[:punct:][:space:]@]+)*$');

-- 도서관
create table LIBRARY(
    LIB_NAME VARCHAR(10) PRIMARY KEY,
    CLOSED VARCHAR(3) NOT NULL,
    CON_NUMBER VARCHAR(11) NOT NULL,
    CONSTRAINT LIBRARY_LIB_NAME_CHECK CHECK (REGEXP_LIKE(LIB_NAME,'^[^[:space:]]+$')),
    CONSTRAINT LIBRARY_CLOSED_CHECK CHECK (REGEXP_LIKE(CLOSED,'^[^[:punct:][:space:]]+$')),
    CONSTRAINT LIBRARY_CON_NUMBER_CHECK CHECK (LENGTH(CON_NUMBER) <= 11)
);
select * from LIBRARY;
delete from library where LIB_NAME='yylibrary';
-- 소장 도서
create table LIBRARY_BOOK(
    ISBN INT(15) PRIMARY KEY,
    TITLE VARCHAR(20) NOT NULL,
    PUBLISHER VARCHAR(10) NOT NULL,
    PUB_DATE DATE NOT NULL,
    AUTHOR VARCHAR(10) NOT NULL,
    CHECK_OUT CHAR(1) DEFAULT 'N',
    DUE_DATE DATE,
    HOLDING_LIB VARCHAR(10) NOT NULL,
    CATE VARCHAR(10) NOT NULL,
    LOC INT(10) NOT NULL,
    IMAGE_URL VARCHAR(2048) default NULL,
    CONSTRAINT LIBRARY_BOOK_HOLDING_LIB_FK FOREIGN KEY (HOLDING_LIB) REFERENCES LIBRARY(LIB_NAME),
    CONSTRAINT LIBRARY_BOOK_CATE_FK FOREIGN KEY (CATE) REFERENCES CATEGORY(CATE_NO),
    CONSTRAINT LIBRARY_BOOK_LOC_FK FOREIGN KEY (LOC) REFERENCES BOOK_LOC(LOC_NO),
    CONSTRAINT LIBRARY_BOOK_CHECK_OUT_CHECK CHECK (CHECK_OUT IN ('Y','N')),
    CONSTRAINT LIBRARY_BOOK_ISBN_CHECK CHECK (ISBN >= 0),
    CONSTRAINT LIBRARY_BOOK_TITLE_CHECK CHECK (REGEXP_LIKE(TITLE,'^[^[:space:]]+$')),
    CONSTRAINT LIBRARY_BOOK_PUBLISHER_CHECK CHECK (REGEXP_LIKE(PUBLISHER,'^[^[:space:]]+$')),
    CONSTRAINT LIBRARY_BOOK_AUTHOR_CHECK CHECK (REGEXP_LIKE(AUTHOR,'^[^[:space:]]+$'))
);

-- 도서 위치
create table BOOK_LOC(
    LOC_NO INT(10) PRIMARY KEY,
    LIBRARY VARCHAR(10) NOT NULL,
    SUPER_LOC VARCHAR(10) NOT NULL,
    SUB_LOC VARCHAR(10) NOT NULL,
    CONSTRAINT BOOK_LOC_LIBRARY_FK FOREIGN KEY (LIBRARY) REFERENCES LIBRARY(LIB_NAME),
    CONSTRAINT BOOK_LOC_LOC_NO_CHECK CHECK (LOC_NO >= 0),
    CONSTRAINT BOOK_LOC_SUPER_LOC_CHECK CHECK (REGEXP_LIKE(SUPER_LOC,'^[^[:space:]]+$')),
    CONSTRAINT BOOK_LOC_SUB_LOC_CHECK CHECK (REGEXP_LIKE(SUB_LOC,'^[^[:space:]]+$'))
);

-- 카테고리
create table CATEGORY(
    CATE_NO INT(10) PRIMARY KEY,
    SUPER_CATE VARCHAR(10) NOT NULL,
    SUB_CATE VARCHAR(10) NOT NULL
    CONSTRAINT CATEGORY_CATE_NO_CHECK CHECK (CATE_NO >= 0),
    CONSTRAINT CATEGORY_SUPER_CATE_CHECK CHECK (REGEXP_LIKE(SUPER_CATE,'^[^[:space:]]+$')),
    CONSTRAINT CATEGORY_SUB_CATE_CHECK CHECK (REGEXP_LIKE(SUB_CATE,'^[^[:space:]]+$'))
);

-- 도서 예약
create table BOOK_RESERVATION(
    ID VARCHAR(10),
    ISBN VARCHAR(15),
    TITLE VARCHAR(20) NOT NULL,
    HOLDING_LIB VARCHAR(10) NOT NULL,
    BOOKING DATETIME DEFAULT NOW() NOT NULL,
    RECEIPT_DATE DATE DEFAULT NULL NOT NULL,
    CONSTRAINT BOOK_RESERVATION_PK PRIMARY KEY(ID, ISBN),
    CONSTRAINT BOOK_RESERVATION_ID_FK FOREIGN KEY (ID) REFERENCES MEMBER(ID),
    CONSTRAINT BOOK_RESERVATION_ISBN_FK FOREIGN KEY (ISBN) REFERENCES LIBRARY_BOOK(ISBN),
    CONSTRAINT BOOK_RESERVATION_TITLE_FK FOREIGN KEY (TITLE) REFERENCES LIBRARY_BOOK(TITLE),
    CONSTRAINT BOOK_RESERVATION_HOLDING_LIB_FK FOREIGN KEY (HOLDING_LIB) REFERENCES LIBRARY(LIB_NAME)
);

-- 도서 대출
create table BOOK_RENT(
    ID VARCHAR(10),
    ISBN VARCHAR(15),
    TITLE VARCHAR(20) NOT NULL,
    HOLDING_LIB VARCHAR(10) NOT NULL,
    RECEIPT_DATE DATE NOT NULL,
    CONSTRAINT BOOK_RENT_PK PRIMARY KEY(ID, ISBN),
    CONSTRAINT BOOK_RENT_ID_FK FOREIGN KEY (ID) REFERENCES MEMBER(ID),
    CONSTRAINT BOOK_RENT_ISBN_FK FOREIGN KEY (ISBN) REFERENCES LIBRARY_BOOK(ISBN),
    CONSTRAINT BOOK_RENT_TITLE_FK FOREIGN KEY (TITLE) REFERENCES LIBRARY_BOOK(TITLE),
    CONSTRAINT BOOK_RENT_HOLDING_LIB_FK FOREIGN  KEY (HOLDING_LIB) REFERENCES LIBRARY(LIB_NAME)
);

-- 희망 도서
create table REQUESTED_BOOK(
    REQ_ID VARCHAR(10),
    ISBN VARCHAR(15),
    REQ_BOOK VARCHAR(20) NOT NULL,
    REQ_DATE DATETIME DEFAULT NOW() NOT NULL,
    CONSTRAINT REQUESTED_BOOK_PK PRIMARY KEY(REQ_ID, ISBN),
    CONSTRAINT REQUESTED_BOOK_REQ_ID_FK FOREIGN KEY (REQ_ID) REFERENCES MEMBER(ID),
    CONSTRAINT REQUESTED_BOOK_ISBN_CHECK CHECK (REGEXP_LIKE(ISBN,'^[^[:space:]]+$'))
);

-- 관심 도서
create table INTEREST_BOOK(
    MEM_ID VARCHAR(10) PRIMARY KEY,
    TITLE VARCHAR(20) NOT NULL,
    ISBN VARCHAR(15) NOT NULL,
    CONSTRAINT INTEREST_BOOK_MEM_ID_FK FOREIGN KEY (MEM_ID) REFERENCES MEMBER(ID),
    CONSTRAINT INTEREST_BOOK_TITLE_FK FOREIGN KEY (TITLE) REFERENCES LIBRARY_BOOK(TITLE),
    CONSTRAINT INTEREST_BOOK_ISBN_FK FOREIGN KEY (ISBN) REFERENCES LIBRARY_BOOK(ISBN)
);

-- 상호대차 신청
create table INTERLIBRARY(
    ID VARCHAR(10) PRIMARY KEY,
    ISBN VARCHAR(15) NOT NULL,
    TITLE VARCHAR(20) NOT NULL,
    HOLDING_LIB VARCHAR(10) NOT NULL,
    REQ_LIB VARCHAR(10) NOT NULL,
    REQ_DATE DATETIME DEFAULT NOW() NOT NULL,
    CONSTRAINT INTERLIBRARY_ID_FK FOREIGN KEY (ID) REFERENCES MEMBER(ID),
    CONSTRAINT INTERLIBRARY_ISBN_FK FOREIGN KEY (ISBN) REFERENCES LIBRARY_BOOK(ISBN),
    CONSTRAINT INTERLIBRARY_TITLE_FK FOREIGN KEY (TITLE) REFERENCES LIBRARY_BOOK(TITLE),
    CONSTRAINT INTERLIBRARY_HOLDING_LIB_FK FOREIGN KEY (HOLDING_LIB) REFERENCES LIBRARY(LIB_NAME),
    CONSTRAINT INTERLIBRARY_REQ_LIB_FK FOREIGN KEY (REQ_LIB) REFERENCES LIBRARY(LIB_NAME)
);

-- 도서 이용내역
create table RENTAL_LIST(
    ID VARCHAR(10),
    ISBN VARCHAR(15),
    TITLE VARCHAR(20) NOT NULL,
    RECEIPT_DATE DATE NOT NULL,
    RETURN_DATE DATE,
    CONSTRAINT RENTAL_LIST_PK PRIMARY KEY(ID, ISBN),
    CONSTRAINT RENTAL_LIST_ID_FK FOREIGN KEY (ID) REFERENCES MEMBER(ID),
    CONSTRAINT RENTAL_LIST_ISBN_FK FOREIGN KEY (ISBN) REFERENCES LIBRARY_BOOK(ISBN),
    CONSTRAINT RENTAL_LIST_TITLE_FK FOREIGN KEY (TITLE) REFERENCES LIBRARY_BOOK(TITLE)
);

-- 도서관 주소
create table ADDRESS(
    LIB_NAME VARCHAR(10) PRIMARY KEY,
    CITY VARCHAR(10) NOT NULL,
    BOROUGH VARCHAR(10) NOT NULL,
    DISTRICT VARCHAR(10) NOT NULL,
    CONSTRAINT ADDRESS_LIB_NAME_FK FOREIGN KEY (LIB_NAME) REFERENCES LIBRARY(LIB_NAME),
    CONSTRAINT ADDRESS_CITY_CHECK CHECK (REGEXP_LIKE(CITY,'^[^[:space:]]+$')),
    CONSTRAINT ADDRESS_BOROUGH_CHECK CHECK (REGEXP_LIKE(BOROUGH,'^[^[:space:]]+$')),
    CONSTRAINT ADDRESS_DISTRICT_CHECK CHECK (REGEXP_LIKE(DISTRICT,'^[^[:space:]]+$'))
);

-- 자료현황
create table HOLDING(
    LIB_NAME VARCHAR(10) PRIMARY KEY,
    GENERAL INT(5) DEFAULT 0,
    NONBOOK INT(5) DEFAULT 0,
    CONSTRAINT HOLDING_LIB_NAME_FK FOREIGN KEY (LIB_NAME) REFERENCES LIBRARY(LIB_NAME),
    CONSTRAINT HOLDING_GENERAL_CHECK CHECK (GENERAL >= 0),
    CONSTRAINT HOLDING_NONBOOK_CHECK CHECK (NONBOOK >= 0)
);

-- 게시판
create table BOARD(
    BOARD_NO INT(28) PRIMARY KEY AUTO_INCREMENT,
    BOARD_TITLE VARCHAR(10) NOT NULL,
    WRITER_ID VARCHAR(10) NOT NULL,
    WRITE_DATE DATETIME DEFAULT NOW() NOT NULL,
    REPLY CHAR(1) DEFAULT 'N',
    OPEN CHAR(1) DEFAULT 'N',
    CONSTRAINT BOARD_WRITER_ID_FK FOREIGN KEY (WRITER_ID) REFERENCES MEMBER(ID),
    CONSTRAINT BOARD_NO_CHECK CHECK (REGEXP_LIKE(BOARD_NO,'^[^[:space:]]+$')),
    CONSTRAINT BOARD_REPLY_CHECK CHECK (REPLY IN ('Y','N')),
    CONSTRAINT BOARD_OPEN_CHECK CHECK (OPEN IN ('Y','N'))
);

-- 게시물내용
create table BOARD_CONTENT(
    CONTENT_NO INT(28) PRIMARY KEY,
    CONTENT TEXT NOT NULL,
    REPLY_CONTENT TEXT default NULL,
    CONSTRAINT BOARD_CONTENT_CONTENT_NO_FK FOREIGN KEY (CONTENT_NO) REFERENCES BOARD(BOARD_NO)
);
